# Generated by Django 4.0.5 on 2022-06-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_img_category_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_img',
            field=models.ImageField(default='', upload_to='Images/user_img/'),
        ),
    ]
