# Generated by Django 4.0.5 on 2022-06-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contact_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_img',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
