# Generated by Django 4.0.5 on 2022-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_contact_user_img_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_img',
            new_name='image',
        ),
    ]
