# Generated by Django 4.0.5 on 2022-06-08 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_cart_quantity_cart_active_cart_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
