# Generated by Django 4.0.5 on 2022-06-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
