# Generated by Django 4.0.5 on 2022-08-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_order_options_alter_order_status_userorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
