# Generated by Django 4.0.5 on 2022-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_order_options_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
