# Generated by Django 4.0.5 on 2022-08-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
